version: "3.5"
services:
  client:
    container_name: pt-demo-client
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client
    volumes:
      - ./client:/frontend
    depends_on:
      - server
    ports:
      - "3000:3000"
  nginx:
    container_name: pt-demo-nginx
    image: nginx
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
    - ./nginx:/etc/nginx/templates
    ports:
    - "8080:80"
    depends_on:
      - client
    environment:
    - NGINX_PORT=80
  server:
    container_name: pt-demo-server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    volumes:
      - ./server:/server
    ports:
      - "8000:8000"
